import { randomUUID } from 'crypto'
import { getDb } from '../db/client.js'
import { emitToTask } from '../websocket/index.js'
import { logger } from '../utils/logger.js'
import type { AgentRole } from '../types/index.js'

const AGENTS: AgentRole[] = ['pm', 'architect', 'engineer', 'qa']

const MOCK_FILES = [
  {
    path: 'README.md',
    content: '# Generated Project\n\nThis project was generated by AI Multi-Agent pipeline.\n',
    language: 'markdown',
  },
  {
    path: 'src/index.ts',
    content: 'console.log("Hello from generated project!")\n',
    language: 'typescript',
  },
]

/**
 * Sleep for a given number of milliseconds.
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

/**
 * Run the full agent pipeline for a given task.
 * Emits WebSocket events at each stage and writes results to the database.
 * @param taskId - The task ID to run the pipeline for
 */
export async function runPipeline(taskId: string): Promise<void> {
  const db = getDb()

  try {
    // Mark task as running
    await db.execute({
      sql: `UPDATE Task SET status = 'running' WHERE id = ?`,
      args: [taskId],
    })

    for (const agent of AGENTS) {
      // Emit agent_start
      emitToTask({ type: 'agent_start', taskId, agent })
      logger.info('Agent started', { taskId, agent })

      // Simulate agent thinking
      await sleep(1000)

      const mockContent = `[${agent.toUpperCase()} Agent] Analysis complete for task ${taskId}`

      // Emit chunk (simulated streaming)
      emitToTask({ type: 'agent_chunk', taskId, agent, chunk: mockContent })

      // Write log to DB
      await db.execute({
        sql: `INSERT INTO AgentLog (id, taskId, agentRole, content, createdAt) VALUES (?, ?, ?, ?, ?)`,
        args: [randomUUID(), taskId, agent, mockContent, new Date().toISOString()],
      })

      // Emit agent_done
      emitToTask({ type: 'agent_done', taskId, agent })
      logger.info('Agent done', { taskId, agent })
    }

    // Write generated files to DB
    for (const file of MOCK_FILES) {
      const fileId = randomUUID()
      await db.execute({
        sql: `INSERT INTO GeneratedFile (id, taskId, path, content, language) VALUES (?, ?, ?, ?, ?)`,
        args: [fileId, taskId, file.path, file.content, file.language],
      })
      emitToTask({ type: 'file_created', taskId, path: file.path })
    }

    // Mark task as done
    await db.execute({
      sql: `UPDATE Task SET status = 'done', finishedAt = ? WHERE id = ?`,
      args: [new Date().toISOString(), taskId],
    })

    emitToTask({ type: 'task_done', taskId, fileCount: MOCK_FILES.length })
    logger.info('Pipeline completed', { taskId })
  } catch (err) {
    logger.error('Pipeline error', { taskId, err })
    await db.execute({
      sql: `UPDATE Task SET status = 'failed', errorMsg = ? WHERE id = ?`,
      args: [err instanceof Error ? err.message : 'Unknown error', taskId],
    })
    emitToTask({ type: 'task_failed', taskId, error: err instanceof Error ? err.message : 'Unknown error' })
  }
}
